### ISSUE TITLE
Fix examples and CI

### ISSUE THREAD

**Issue by FelixStege** [RWTH-EBC/AixCaliBuHA#52]
The Modelica models for the examples are dependent on the MSL 3.2.3. Since AixLib is using version 4.0.0, we should update these models.

Additionally, the CI is failing, due to changes in the templates. We should update the `.yml` accordingly.

**Comment by HvanderStok** [comment]
Also an issue in ebcpy [https://github.com/RWTH-EBC/ebcpy/issues/111](url) causes the CI to fail.
